// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace CartaoCredito.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tab_pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tab_pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201601022354226_add_tab_pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
